[tool.azure-sdk-build]
mypy = true
type_check_samples = false
verifytypes = true
pyright = false
[[tool.azure-sdk-build.optionalenv]]
environment = no_requests
uninstall = ["requests"]
install = []
test-tools = true
dev-reqs = true

[[tool.azure-sdk-build.optionalenv]]
environment = no_aiohttp
uninstall = ["aiohttp"]
install = []
test-tools = true
dev-reqs = true
